name: Build and Maybe Deploy

on:
  push:
    branches:
      - develop

env:
  PYTHON_VERSION: "3.13"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run Checks and tests
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          build-args: |
            version=${{ env.PYTHON_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
